### ISSUE TITLE
Broken Link in Readme

### ISSUE THREAD

**Issue by jzabroski** [aidanmelen/assume_role#1]
https://aws.amazon.com/answers/account-management/aws-multi-account-security-strategy/

Thanks for the description of the multi-account security strategy, though.  Trying to implement best practices and coming across stuff like this is super helpful.

**Comment by aidanmelen** [comment]
Hey @jzabroski, Happy to help. It looks like that doc is now gone from AWS. too bad. Most of the information covered there is now covered [here](https://d0.awsstatic.com/aws-answers/AWS_Multi_Account_Security_Strategy.pdf)

I should also mention that I have moved support of this project to a new project called [awscli-bastion](https://github.com/aidanmelen/awscli_bastion). I am actively deving on that project. Currently in the process of [hypermodernizing](https://cjolowicz.github.io/posts/hypermodern-python-01-setup/) the project on this [branch](https://github.com/aidanmelen/awscli_bastion/tree/hypermodernize).

One cool thing about awscli-bastion is the [minimal.py script](https://github.com/aidanmelen/awscli_bastion#bastion-minimal). This is a 100 lines of python that does the core automation of the larger awscli-bastion tool. I would check that out if you are new to the whole using STS credentials from the bastion account to assume-roles into business unit accounts without need to punch in your MFA multiple times.

**Comment by aidanmelen** [comment]
@jzabroski You might want to checkout this [reInvent video](https://youtu.be/71fD8Oenwxc?t=2348) is from 2017, but I think the same rules still apply.

**Comment by jzabroski** [comment]
@aidanmelen Thanks for all the links.  So, I am a bit embarassed, I had never heard of the phrase "bastion host" before.  I found https://codingbee.net/aws-csa-associate/aws-bastion-hosts but I don't quite understand why it's needed to allow me to have temporary access credentials (I've done a ton of reading on AWS security the last week, and it's not really _clicking_ yet - but it's starting to click).  Where I am at is I realize that if I call `curl http://169.254.169.254/latest/meta-data/iam/security-credentials` from an Amazon Workspace machine, I get a 404, because (as best as I can tell the reason is) I'm not on an EC2 Instance.

But... I don't want to have permanent access keys/secret keys stored on my machine.  It's pretty hacky, and it causes my C# code to have two paths through creating an `IAmazonS3` client - one for my dev machine that uses access keys and secret keys, one for integration/production that uses temporary access credentials stored in the EC2 instance metadata.  So I was looking for a way to convince Amazon I have EC2 instance metadata.  But that may be an x-y problem.

**Comment by aidanmelen** [comment]
Okay okay. Let me try to help. There are three things here

# EC2 Bastion Host

## Jargon
* [bastion](https://en.wikipedia.org/wiki/Bastion)
* sometimes this is referred to as a **jump box**

## Description

This is referring to an EC2 Bastion Host that is deployed into a public subnet (I.E. a subnet with a route to an Internet Gateway). The EC2 Bastion Host allows setup an SSH proxy into resources running in a private subnet. Here are the offical docs on this.

## Links
* [Linux Bastion Hosts on the AWS Cloud](https://docs.aws.amazon.com/quickstart/latest/linux-bastion/architecture.html)

---

# EC2 Bastion (AWS) Account

* Long-lived keys are the AWS_ACCESS_KEY and AWS_SECRET_ACCESS_KEY

## Description

This is a term coined by [Graham Jenson at Coinbase in 2017](https://blog.coinbase.com/you-need-more-than-one-aws-account-aws-bastions-and-assume-role-23946c6dfde3). This is similar to the EC2 bastion host, but in this case an AWS Account is the "bastion" and instead of being a bastion for networking traffic -- it is a bastion for IAM Roles across a AWS with multiple account.

## Why would you use a bastion account?

It is assumed that you only wish to manage a single set of IAM user or have a single account federated with an SSO provider. So the AWS bastion account allows to you manage access IAM users, groups, and cross-account roles in one place. The alternative would be IAM users on every single account, yuck. You can see how that would be problematic if you have 100s of AWS accounts.

We want to minimize our blast radius for long-lived keys. So we do this by only putting them on the Bastion by associating them with an IAM users. We use a layered security approach to protect these LLK's with MFA. This means that you can only assume a cross account role if the MFA is enabled. So in the off chance that you accidentally push you LLK's to github, you won't be totally hosed because those keys give access to an IAM user on the AWS Bastion account that only has permissions to assume roles and you can only assume those roles if MFA is enabled. So you are still protected. Graham Jenson talks about this in more detail in his blog post.

## Links

* [You need more than one AWS account: AWS bastions and assume-role](https://blog.coinbase.com/you-need-more-than-one-aws-account-aws-bastions-and-assume-role-23946c6dfde3)

---

# IAM Cross-account roles and Service Roles.

# Description

* IAM Cross-account role: This is used to provide AWS resources in one account access AWS resources in another AWS account by configuring `trusting` roles which trust a role(s) in another AWS account and `trusted` roles. This is the trust relationship that the AWS Bastion Account relies on AKA the Bastion Account has a `trusted` role that the Business unit accounts have a corresponding `trusting` role.

* IAM Service Roles role: Unlike Cross account roles, this is used in a single account. Service roles allow an AWS resource(s) (such as EC2, EKS, Lambda, .etc) permissions to used other AWS resources (such as S3, ECR, Lambda, etc.) from the same account.

* I don't mean to complicate things further, but you can have a Service role on the Trusting account trust the `trusting` role. This will allow a a trusted account to access a specific AWS resource in another account.

So for you use case, you have a program running on an EC2 instance that needs to interact with S3. Okay perfect, just slap a service role that has privileges for S3 on that EC2. Then if you will automagically be able to hit the S3 API from your EC2 instance. Here is an [AWS post](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-instance-access-s3-bucket) on that topic.

Hope that helps clear things up.

**Comment by jzabroski** [comment]
@aidanmelen Thanks.  But one thing isn't clear to me:

> So for you use case, you have a program running on an EC2 instance that needs to interact with S3. Okay perfect, just slap a service role that has privileges for S3 on that EC2. Then if you will automagically be able to hit the S3 API from your EC2 instance. Here is an [AWS post](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-instance-access-s3-bucket) on that topic.

In my use case, I do development on an Amazon Workspace machine, and then deploy to an EC2 instance (for test and production).  How can I debug from my Amazon Workspace, since my Amazon Workspace will return a 404 for `curl http://169.254.169.254/latest/meta-data/iam/security-credentials` (because it is not an EC2 instance)?  If I use access keys and secret keys, I can debug from my Amazon Workspace, but then I introduce security risk by having keys laying around unencrypted (Why AWS didn't use Windows Data Protection API for this stuff and use machine key encryption to encrypt the files, I have no idea).  I was looking for how to get STS to give me a temporary access credential from my Amazon Workspace, but it seems like that scenario isn't supported - but I feel like _somebody_ must have figured out a workaround, which I _thought_ was your solution.

I am learning more and more each day, and your last reply accelerated my learning a 100x, so if I can donate something to you (reddit badge even?), let me know.  Incidentally, I saw you work at PluralSight, and I know a few people there in the Boston office.

**Comment by jzabroski** [comment]
Incidentally, Amazon _just_ followed up with a ticket I opened, and acknowledged this as a real usability issue, and something they would look into smoothing over.

**Comment by aidanmelen** [comment]
check this [link](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) out and see if that satisfies your use case.
